### ISSUE TITLE
Remove scientific format from max INL and DNL annatation

### ISSUE THREAD

**Issue by vlahtin** [TheSDK-blocks/dac_analyser#1]
The scientific format should be removed if the value is over e.g. e-02.

**Comment by atammine** [comment]
Please assign me to the issue.

**Comment by atammine** [comment]
@vlahtin Do you mean "...if the value is *under* e.g. e-02."? We want small values appear in float notation and large values scientific notation?

**Comment by atammine** [comment]
@vlahtin Never mind, I think we want the small values in sci notation and large values float, as INL almost never is many.

**Comment by vlahtin** [comment]
Yep exactly, small values, e.g. 0.000352 in scientific, but values such as 0.32 or 1.25 just as floats. I think 2 or 3 decimals should be accurate enough.

**Comment by vlahtin** [comment]
Sorry for the unclear short description of the issue

**Comment by vlahtin** [comment]
Fixed in https://github.com/TheSDK-blocks/dac_analyser/pull/2
